theme: jekyll-theme-minimal

# Customize the style
title: [Yin's Homepage]
#description: [The description is left with empty because the owner of the page is currently searching for her life purpose.]
description: [Welcome to my homepage and thanks for starting the conversation XD ]
baseurl: /

#assets
logo: /assets/img/logo_new.png

#config
blog: true
project: true
github.is_user_page: true
google_analytics: true
