theme: jekyll-theme-minimal

# Customize the style
title: [Yin's Homepage]
#description: [The description is left with empty because the owner of the page is currently searching for her life purpose.]
description:[-Not Found-]
baseurl: /

#assets
logo: /assets/img/logo.png

#config
blog: true
project: true
github.is_user_page: true
